// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HowToDoBlazorSystem.Entities;

internal partial class Order
{
    [Key]
    public int OrderID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    public int StoreID { get; set; }

    public int CustomerID { get; set; }

    public int? PickerID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PickedDate { get; set; }

    public bool Delivery { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    [Column(TypeName = "money")]
    public decimal GST { get; set; }

    [ForeignKey("CustomerID")]
    [InverseProperty("Orders")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderList> OrderLists { get; set; } = new List<OrderList>();

    [ForeignKey("StoreID")]
    [InverseProperty("Orders")]
    public virtual Store Store { get; set; }
}